PetShopProject/Models/AdministratorViewModel.cs
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using PetShopProject.Repositories;

namespace PetShopProject.Models
{
    public class AdministratorViewModel
    {
        public IEnumerable<Category>? Categories { get; set; }
        public IEnumerable<Animal>? Animals { get; set; }

    }

   
}

PetShopProject/Controllers/Administrator/AdministratorController.cs
using Microsoft.AspNetCore.Mvc;
using PetShopProject.Models;
using PetShopProject.Repositories;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Hosting.Internal;
using NuGet.Protocol.Core.Types;

public class AdministratorController : Controller
{
    private readonly IAnimalRepository _animalRepository;
    private readonly IWebHostEnvironment _hostingEnvironment;

    public AdministratorController(IAnimalRepository animalRepository, IWebHostEnvironment hostingEnvironment)
    {
        _animalRepository = animalRepository;
        _hostingEnvironment = hostingEnvironment;
    }

    public IActionResult Index(int? selectedCategoryId) // Shows the full list of animals by default: manageble to sort by category
    {
        var categories = _animalRepository.GetCategories();
        IEnumerable<Animal> animals;

        if (selectedCategoryId.HasValue && selectedCategoryId.Value != 0)
        {
            animals = _animalRepository.GetAnimals().Where(animal => animal.CategoryId == selectedCategoryId.Value);
        }
        else
        {
            animals = _animalRepository.GetAnimals();
        }

        var viewModel = new AdministratorViewModel
        {
            Categories = categories,
            Animals = animals
        };

        ViewBag.SelectedCategoryId = selectedCategoryId.HasValue ? selectedCategoryId.Value : 0;

        return View(viewModel);
    }




    [HttpGet] //retrieves the prompt for adding an animal
    public IActionResult EditAnimal(int id)
    {
        var animal = _animalRepository.GetAnimal(id);
        if (animal == null)
        {
            return NotFound();
        }

        var categories = _animalRepository.GetCategories().Select(c => new SelectListItem
        {
            Value = c.CategoryId.ToString(),
            Text = c.Name
        });

        var viewModel = new AnimalEditViewModel
        {
            Animal = animal,
            AnimalName = animal.Name,
            Age = animal.Age,
            Description = animal.Description,
            SelectedCategoryId = animal.CategoryId,
            Categories = categories
        };

        return View(viewModel);
    }



    [HttpPost] //POST mehod for editing an animal, retrieves the exissting details, I chose a unique way of uploading the image
    public IActionResult EditAnimal(int id, Animal animal, IFormFile pictureName)
    {
        if (ModelState.IsValid)
        {
            if (pictureName != null)
            {
                // Generate a unique file name (e.g., using GUID)
                string fileName = Guid.NewGuid().ToString() + Path.GetExtension(pictureName.FileName);

                // Specify the path to save the file
                var filePath = Path.Combine(_hostingEnvironment.WebRootPath, "images", fileName);

                // Save the file
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    pictureName.CopyTo(fileStream);
                }

                // Update the animal object with the new file name
                animal.PictureName = fileName;
            }

            _animalRepository.UpdateAnimal(animal);
            TempData["SuccessMessage"] = "Animal updated successfully";
            return RedirectToAction("index");
        }
        else
        {
            var categories = _animalRepository.GetCategories().Select(c => new SelectListItem
            {
                Value = c.CategoryId.ToString(),
                Text = c.Name
            });

            var viewModel = new AnimalEditViewModel
            {
                Animal = animal,
                AnimalName = animal.Name,
                Age = animal.Age,
                Description = animal.Description,
                SelectedCategoryId = animal.CategoryId,
                Categories = categories
            };

            return View(viewModel);
        }
    }




    [HttpGet] //retrieves the prompt for adding an animal
    public IActionResult InsertAnimal()
    {
        var categories = _animalRepository.GetCategories();
        var viewModel = new NewAnimalViewModel
        {
            Categories = new SelectList(categories, "CategoryId", "Name"),

        };

        return View(viewModel);
    }
    [HttpPost] //similar approach as the POST method for inserting/adding a new animal
    public IActionResult InsertAnimal(NewAnimalViewModel viewModel)
    {
        if (!ModelState.IsValid)
        {
            viewModel.Categories = new SelectList(_animalRepository.GetCategories(), "CategoryId", "Name");
            return View(viewModel);
        }

        string fileName = null;

        if (viewModel.PictureName != null)
        {
            fileName = Guid.NewGuid().ToString() + Path.GetExtension(viewModel.PictureName.FileName);
            var filePath = Path.Combine(_hostingEnvironment.WebRootPath, "images", fileName);

            using (var fileStream = new FileStream(filePath, FileMode.Create))
            {
                viewModel.PictureName.CopyTo(fileStream);
            }
        }

        var newAnimal = new Animal
        {
            Name = viewModel.AnimalName,
            Age = viewModel.Age,
            Description = viewModel.Description,
            PictureName = fileName, 
            CategoryId = viewModel.CategoryId
        };

        _animalRepository.AddAnimal(newAnimal);

        TempData["SuccessMessage"] = "Animal added successfully";

        return RedirectToAction("Index");
    }



    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult DeleteAnimal(int id)  //deleting animal from database
    {
        var animal = _animalRepository.GetAnimal(id);

        if (animal == null)
        {
            return NotFound(); 
        }

        _animalRepository.DeleteAnimal(animal);

        TempData["SuccessMessage"] = "Animal successfully deleted"; 

        return RedirectToAction("Index");

    }
}

PetShopProject/Views/Administrator/EditAnimal.cshtml
@model PetShopProject.Models.AnimalEditViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Edit Animal";
}
<link rel="stylesheet" href="~/css/LayoutStyles.css">
<div class="container">
    @if (TempData["SuccessMessage"] != null)
    {
        <div class="alert alert-success" role="alert">
            @TempData["SuccessMessage"]
        </div>
    }
  
    <h2>Edit Animal</h2>

    <form asp-action="EditAnimal" asp-controller="Administrator" method="post" enctype="multipart/form-data" onsubmit="return confirmSaveChanges();">
        <input type="hidden" asp-for="Animal.AnimalId" />

        <div class="form-group">
            <label asp-for="Animal.Name"></label>
            <input asp-for="Animal.Name" class="form-control" />
            <span asp-validation-for="Animal.Name" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Animal.Age"></label>
            <input asp-for="Animal.Age" class="form-control" />
            <span asp-validation-for="Animal.Age" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Animal.CategoryId"></label>
            <select asp-for="Animal.CategoryId" asp-items="Model.Categories" class="form-control">
                <option value="">-- Select Category --</option>
            </select>
            <span asp-validation-for="Animal.CategoryId" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="PictureName"></label>
            <input type="file" asp-for="PictureName" class="form-control" onchange="previewFile()" accept=".jpg,.jpeg" />
            <span asp-validation-for="PictureName" class="text-danger"></span>
            <img id="previewImage" src="@Url.Content("~/images/" + Model.Animal.PictureName)" alt="Image Preview" style="max-width: 200px; max-height: 200px;" />
        </div>

        <div class="form-group">
            <label asp-for="Animal.Description"></label>
            <textarea asp-for="Animal.Description" class="form-control"></textarea>
            <span asp-validation-for="Animal.Description" class="text-danger"></span>
        </div>

        <button type="submit" class="btn btn-success">Update</button>
    </form>

    <a asp-action="Index">Back to List</a>

    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
    <script>
        function previewFile() {
            var preview = document.getElementById('previewImage');
            var file = document.querySelector('input[type=file]').files[0];
            var reader = new FileReader();

            reader.onloadend = function () {
                preview.src = reader.result;
            }

            if (file) {
                reader.readAsDataURL(file);
            } else {
                preview.src = "";
            }
        }
        function confirmSaveChanges() {
            var userConfirmed = confirm('Are you sure you want to save your changes to this animal?');

            if (userConfirmed) {
                return true;
            } else {
                return false;
            }
        }
    </script>
</div>

PetShopProject/Views/Administrator/Index.cshtml
@model PetShopProject.Models.AdministratorViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Admin Page";
    int selectedCatId = ViewBag.SelectedCategoryId;
}
@if (TempData["SuccessMessage"] != null)
{
    <div id="successMessage" class="alert alert-success">
        @TempData["SuccessMessage"]
    </div>
}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

<div class="d-flex justify-content-center align-items-center flex-column">
    @Html.AntiForgeryToken()

    <h2>Administrator Page</h2>

    <div class="d-flex justify-content-between align-items-center mt-4" style="width: 100%;">
        <div style="text-align: left;">
            <label for="categoryDropdown" style="margin-right: 10px;">Filter by Category:</label>
            <select id="categoryDropdown" class="category-selection">
                <option value="0">All Categories</option>
                @foreach (var category in Model.Categories)
                {
                    <option value="@category.CategoryId" selected="@(category.CategoryId == selectedCatId)">
                        @category.Name
                    </option>
                }
            </select>
        </div>
        <div style="text-align: right;">
            <a href="/Administrator/InsertAnimal" class="btn btn-primary">Add New Animal</a>
        </div>
    </div>


<table class="table">
    <thead>
        <tr>
            <th>Animal ID</th>
            <th>Name</th>
            <th>Age</th>
            <th>Category</th>
            <th>Description</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var animal in Model.Animals)
        {
            <tr>
                <td>@animal.AnimalId</td>
                <td>
                    <img src="~/images/@animal.PictureName" alt="@animal.Name" style="height: 50px; width: 50px; object-fit: cover;">
                    @animal.Name
                </td>
                <td>@animal.Age</td>
                <td>@Model.Categories.FirstOrDefault(c => c.CategoryId == animal.CategoryId)?.Name</td>
                    <td>
                        <span class="description-summary" data-description="@animal.Description">
                            @Html.Raw(@animal.Description.Substring(0, Math.Min(100, @animal.Description.Length))) @if (@animal.Description.Length > 100)
                            {
                                <a href="#" class="expand-description">[...]</a>
                            }
                        </span>
                        <span class="description-full" style="display: none;"></span>

                    </td>
                    <td>
                        <a href="/Administrator/EditAnimal/@animal.AnimalId" class="btn btn-primary ">Edit</a>
                        <a href="#" class="btn btn-danger delete-link" data-animal-id="@animal.AnimalId" onclick="confirmDelete(this)">Delete</a>


                    </td>

            </tr>
        }
    </tbody>
</table>

    <a href="javascript:history.go(-1)" class="btn btn-outline-secondary">Back</a>

<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
    <script>
        $(document).ready(function () {
            $(".delete-link").on("click", function () {
                var animalId = $(this).data("animal-id");
                var confirmation = confirm("Are you sure you want to delete this animal?");

                if (confirmation) {
                    var formData = new FormData();
                    formData.append('id', animalId);

                    fetch('/Administrator/DeleteAnimal', {
                        method: 'POST',
                        headers: {
                            'RequestVerificationToken': document.querySelector('input[name="__RequestVerificationToken"]').value, 
                            'X-Requested-With': 'XMLHttpRequest'
                        },
                        body: formData
                    })
                        .then(response => {
                            if (response.ok) {
                                window.location.href = '/Administrator/Index';
                            } else {
                                alert('Error: Unable to delete the animal');
                            }
                        });
                }
            });

        });

        $(document).ready(function () {
            var selectedCategoryId = '@ViewBag.CategoryId'; // Get the selected category ID from ViewBag
            if (selectedCategoryId) {
                $('#categoryDropdown').val(selectedCategoryId); 
            }

            $('.category-selection').on('change', function () {
                var categoryId = $(this).val();
                window.location.href = '/Administrator/Index?selectedCategoryId=' + categoryId;
            });
        });
        $(document).ready(function () {
            $(".expand-description").on("click", function (e) {
                e.preventDefault(); 

                var descriptionSummary = $(this).parent();
                var descriptionFull = descriptionSummary.siblings(".description-full");

                if (descriptionFull.is(":visible")) {
                    descriptionFull.hide();
                    descriptionSummary.show();
                } else {
                    var fullDescriptionText = descriptionFull.text();
                    descriptionSummary.hide();
                    descriptionFull.text(descriptionSummary.data("description")).show();
                    descriptionSummary.data("description", fullDescriptionText);
                }
            });
        });
        setTimeout(function () {
            $("#successMessage").fadeOut(500); 
        }, 4000); 

    </script>
  
  
  

PetShopProject/Views/Administrator/InsertAnimal.cshtml
@model PetShopProject.Models.NewAnimalViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Add New Animal";
}

<div class="container">
   

    <h2>Add New Animal</h2>

    <form asp-action="InsertAnimal" asp-controller="Administrator" method="post" enctype="multipart/form-data" onsubmit="return confirm('Are you sure you want to insert this animal?');">
        <div class="form-group">
            <label asp-for="AnimalName"></label>
            <input asp-for="AnimalName" class="form-control" />
            <span asp-validation-for="AnimalName" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Age"></label>
            <input asp-for="Age" class="form-control" />
            <span asp-validation-for="Age" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="CategoryId"></label>
            <select asp-for="CategoryId" asp-items="Model.Categories" class="form-control">
                <option value="">-- Select Category --</option>
            </select>
            <span asp-validation-for="CategoryId" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="PictureName"></label>
            <input type="file" asp-for="PictureName" class="form-control" onchange="updateImagePreview()" />
            <span asp-validation-for="PictureName" class="text-danger"></span>
        </div>

        <div class="form-group">
            <img id="previewImage" src="#" alt="Image preview" style="max-height: 200px;" />
        </div>

        <div class="form-group">
            <label asp-for="Description"></label>
            <textarea asp-for="Description" class="form-control"></textarea>
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>

        <button type="submit" class="btn btn-success">Insert</button>
    </form>

    <a asp-action="Index">Back to List</a>
    @if (TempData["SuccessMessage"] != null)
    {
        <div class="alert alert-success mt-3" role="alert">
            @TempData["SuccessMessage"]
        </div>
    }
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
    <script>
        function updateImagePreview() {
            var file = document.getElementById('PictureName').files[0];
            var reader = new FileReader();
            reader.onloadend = function () {
                document.getElementById('previewImage').src = reader.result;
            }
            if (file) {
                reader.readAsDataURL(file);
            } else {
                document.getElementById('previewImage').src = "";
            }
        }
        </script>

</div>